### ISSUE TITLE
Minimum password size warning do not contains ${min_chars} insted of the value

### ISSUE THREAD

**Issue by PriyanshuRj** [plone/volto#4590] opened 2023-03-21 18:50 UTC
**Describe the bug**
The add user form in the Volto frontend when given a password of small length shows the warning where the minimum no. of letter number is mentioned as ${min_chars} insted of the number.

**To Reproduce**

1. Go to volto fronend 
2. Click on 'user icon on the bottom left corner after loging in 
3. In the users section click on users and then click on the add user icon in the left panel.
4. Fill the details for the new user with a small password size let be of 3 letters
5. The application gives an error "Your password must contain at least ${min_chars} characters. "

**Expected behaviour**
There should be a number let `8` insted of the  value `${min_chars}` .

**Screenshots**

![Screenshot from 2023-03-22 00-12-31](https://user-images.githubusercontent.com/76838551/226711382-76cb6296-91b2-4af6-9f88-4c88d80dce9b.png)

**Comment by wesleybl** [comment] 2023-03-21 18:56
Duplicate of #4395. This issue has now been fixed.

**Closed by wesleybl** 2023-03-21 18:56 UTC
Labels: 01 type: bug
