### ISSUE TITLE
It is not possible to configure restricted addable types per context

### ISSUE THREAD

**Issue by tiberiuichim** [plone/volto#3801] opened 2022-10-26 12:53 UTC
![image](https://user-images.githubusercontent.com/141568/198030942-aa0888fd-b235-4bb1-99b0-d1a1aa740182.png)

**Comment by erral** [comment] 2022-10-26 15:43
I think there is endpoint in plone.restapi to handle this yet.

> Message ID: ***@***.***>
>


-- 
Mikel Larreategi
***@***.***

CodeSyntax
Azitain industrialdea, 3-K  - Eibar
Tfnoa.: +34 943821780

**Comment by davisagli** [comment] 2022-10-26 15:46
This is a duplicate of #26 and #2617. It depends on https://github.com/plone/plone.restapi/issues/334

**Closed** 2022-10-26 19:19 UTC
Labels: 01 type: bug
