### ISSUE TITLE
there is a issue with a command

### ISSUE THREAD

**Issue by rahulrangers** [plone/volto#5583] opened 2023-12-29 04:14 UTC
There is a issue when i want to create volto project using this command yo @plone/volto
the error-
Retrieving Volto's yarn.lock
✖ An error occured while running @plone/volto:app#prompting
Error @plone/volto my-volto --canary 

TypeError [ERR_INVALID_ARG_TYPE]: The "code" argument must be of type number. Received type string ('ETIMEDOUT')
    at process.set [as exitCode] (node:internal/bootstrap/node:123:9)
    at process.exit (node:internal/process/per_thread:188:24)
    at onError (/home/rahulreddy/.nvm/versions/node/v20.10.0/lib/node_modules/yo/lib/cli.js:117:11)
    at /home/rahulreddy/.nvm/versions/node/v20.10.0/lib/node_modules/yo/lib/cli.js:168:54
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async init (/home/rahulreddy/.nvm/versions/node/v20.10.0/lib/node_modules/yo/lib/cli.js:168:5)
    at async pre (/home/rahulreddy/.nvm/versions/node/v20.10.0/lib/node_modules/yo/lib/cli.js:83:3)
    at async /home/rahulreddy/.nvm/versions/node/v20.10.0/lib/node_modules/yo/lib/cli.js:193:3
KIndly check this out

**Comment by stevepiercy** [comment] 2023-12-29 10:08
What instructions did you follow? For creating a Volto project, you should follow the official documentation at https://6.docs.plone.org/install/install-from-packages.html.

Also the issue tracker is the last place you should go for support. Go to the [Community Forum](https://community.plone.org/) instead and read https://plone.org/community/support/how-to-ask-for-help for good advice.

I'm closing this because there is not sufficient information to reproduce what you did.

**Closed by stevepiercy** 2023-12-29 10:08 UTC
Labels: 01 type: bug
