### ISSUE TITLE
Bootstrap process (still) broken

### ISSUE THREAD

**Issue by zopyx** [plone/volto#1230] opened 2020-02-22 12:48 UTC
```
(volto)ajung@zopyx-nuc ~/src/volto $ npm install -g yarn
/home/ajung/src/volto/bin/yarn -> /home/ajung/src/volto/lib/node_modules/yarn/bin/yarn.js
/home/ajung/src/volto/bin/yarnpkg -> /home/ajung/src/volto/lib/node_modules/yarn/bin/yarn.js
+ yarn@1.22.0
added 1 package in 0.338s
(volto)ajung@zopyx-nuc ~/src/volto $ npm install -g @plone/create-volto-app
/home/ajung/src/volto/bin/create-volto-app -> /home/ajung/src/volto/lib/node_modules/@plone/create-volto-app/bin/create-volto-app.js
+ @plone/create-volto-app@3.2.1
added 49 packages from 14 contributors in 1.892s
(volto)ajung@zopyx-nuc ~/src/volto $ !create
create-volto-app myvoltoproject
/home/ajung/src/volto/lib/node_modules/@plone/create-volto-app/volto-starter-kit

Creating myvoltoproject...

> Success! Created files for "myvoltoproject" Volto app

  Installing npm modules:
    @plone/volto

> Error! Failed to install @plone/volto, try again.
undefined
(volto)ajung@zopyx-nuc ~/src/volto $ node --version
v12.5.0
(volto)ajung@zopyx-nuc ~/src/volto $ npm --version
6.9.0
 ```

**Comment by zopyx** [comment] 2020-02-22 12:55
Same error on a different Linux box

**Comment by tisto** [comment] 2020-02-22 15:07
I can confirm the problem:

````
npm install -g @plone/create-volto-app
/Users/timo/.nvm/versions/node/v12.14.1/bin/create-volto-app -> /Users/timo/.nvm/versions/node/v12.14.1/lib/node_modules/@plone/create-volto-app/bin/create-volto-app.js
npm WARN notsup Unsupported engine for @plone/create-volto-app@3.2.1: wanted: {"node":"^8 || ^10"} (current: {"node":"12.14.1","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: @plone/create-volto-app@3.2.1

+ @plone/create-volto-app@3.2.1
added 49 packages from 14 contributors in 6.261s
➜  workspace create-volto-app myvoltoproject
/Users/timo/.nvm/versions/node/v12.14.1/lib/node_modules/@plone/create-volto-app/volto-starter-kit

Creating myvoltoproject...

> Success! Created files for "myvoltoproject" Volto app

  Installing npm modules:
    @plone/volto

> Error! Failed to install @plone/volto, try again.
undefined
`````

Though, in my trace the problem is obvious. I am using Node 12 while create-volto-app only supports Node 8 and 10. We have to fix this.

Note that this is actually a create-volto-app issue.

**Comment by tisto** [comment] 2020-02-22 15:09
@zopyx could you please try to install create-volto-app@4.0.0-alpha.8? Volto 4 will be released very soon (next days) and most likely we won't put much effort into Volto 3 or create-volto-app 3.x.

**Comment by sneridagh** [comment] 2020-02-22 18:39
@zopyx you should use the @alpha version of @plone/create-volto-app

**Comment by sneridagh** [comment] 2020-02-22 18:40
In few days all this confusion current/alpha versions will be over.

**Closed by sneridagh** 2020-02-22 18:40 UTC

**Comment by tisto** [comment] 2020-02-22 19:24
@sneridagh we need to find a way to test this properly. What worries me here is that we do not have any CI job that notifies us if things are broken. IMHO we need something like the tests I wrote for bobtemplates.plone that execute all steps necessary in the installation process and then check the result.

**Comment by sneridagh** [comment] 2020-02-22 19:27
It's in place, for alpha and it's working. Deps change can make the build break, that is what probably happened to 3.x.x versions.

https://github.com/plone/create-volto-app/blob/master/.travis.yml#L44

**Comment by sneridagh** [comment] 2020-02-22 19:31
@zopyx I just tried out 

`npx @plone/create-volto-app 3dotx`

and worked well, with Node 10.x as @tisto pointed out, most probably you are using 12.x when building the old 3.x.x branch which was supposed to work only with 8.x and 10.x

**Comment by tisto** [comment] 2020-02-22 19:43
@sneridagh yeah. I get the problem. We have two repos who are tightly coupled and we test them individually. We change something in Volto, this breaks create-volto-app and we are never notified because the build is not triggerd. We either have to write a mr.roboto (no!) or merge the two projects into one repo and use lerna to handle multiple projects in a single repo.
