### ISSUE TITLE
cypress test failed because of cypress/videos/blocks.js

### ISSUE THREAD

**Issue by giuliaghisini** [plone/volto#1120] opened 2020-01-21 08:45 UTC
### These pull-requests fails because videos/block-text.js test fails.
Please fix that test. 
**Pull requests:**

- Fix remove all subjects **#1114** (fix-remove-all-subjects)
- build(add commitzen): add commitzen for consistent git commit messages **#1112** (commitizen)
- remove title option from shown columns dropdown in contents view **#1108** (contents-table-columns)

The test in cypress/videos/blocks.js fails and blocks above pull-requests.
This is the failing test log:

 
/home/travis/build/plone/volto/cypress/videos/blocks.js.mp4
                                                                                                    
  Running:  blocks.js                                                                       (5 of 9)
  Blocks Tests
    ✓ Add text block (4594ms)
TypeError: Cannot read property 'properties' of null
    at new t (/home/travis/build/plone/volto/build/server.js:1:330942)
    at d (/home/travis/build/plone/volto/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:320)
    at Za (/home/travis/build/plone/volto/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:39:16)
    at a.b.render (/home/travis/build/plone/volto/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:476)
    at a.b.read (/home/travis/build/plone/volto/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:18)
    at renderToString (/home/travis/build/plone/volto/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:54:364)
    at /home/travis/build/plone/volto/build/server.js:1:415470
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
(node:6004) UnhandledPromiseRejectionWarning: Invariant Violation: [React Intl] Could not find required `intl` object. <IntlProvider> needs to exist in the component ancestry.
    at invariant (/home/travis/build/plone/volto/node_modules/invariant/invariant.js:40:15)
    at Object.invariantIntlContext (/home/travis/build/plone/volto/node_modules/react-intl/dist/utils.js:48:5)
    at Object.children (/home/travis/build/plone/volto/node_modules/react-intl/dist/components/injectIntl.js:35:21)
    at a.b.render (/home/travis/build/plone/volto/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:47:125)
    at a.b.read (/home/travis/build/plone/volto/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:18)
    at renderToString (/home/travis/build/plone/volto/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:54:364)
    at /home/travis/build/plone/volto/build/server.js:1:416114
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
(node:6004) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6004) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    1) "before each" hook for "Add Video Block with YouTube Video"
  1 passing (39s)
  1 failing
  1) Blocks Tests "before each" hook for "Add Video Block with YouTube Video":
     CypressError: cy.request() failed on:

**Comment by tisto** [comment] 2020-01-21 12:54
@giuliaghisini we are constantly working on improving our Cypress tests and making them more resilient. Please add links to failing Travis jobs and I will have a look. Fixes to make our Cypress tests more stable are always welcome as well! :)

**Comment by pnicolli** [comment] 2020-01-21 13:37
Example: https://travis-ci.org/plone/volto/jobs/636896878
It actually looks like it's tied to random Bad Request responses received from Plone.

**Comment by tisto** [comment] 2020-01-21 19:01
Yeah. I saw those bad request quite frequently. Those are related to test setup/teardown problems I guess. The problem is that I am not too familiar with the robot server backend. Maybe @datakurre can give us some pointers...

**Comment by sneridagh** [comment] 2020-01-24 21:04
Tried to fix it by:
https://github.com/plone/volto/pull/1134
Since it seems that the next beforeEach enters before the previous teardown has happened.

Let's see how it goes.

**Comment by sneridagh** [comment] 2020-01-31 16:43
Didn’t see the error in latest builds, will keep it open some days more

**Comment by sneridagh** [comment] 2020-02-02 11:45
Closing, since it seems it was fixed.

**Closed by sneridagh** 2020-02-02 11:45 UTC
Labels: 01 type: bug, 11 prio: blocker, 12 prio: high
