### ISSUE TITLE
Choice Field not polulated with correct values

### ISSUE THREAD

**Issue by pbauer** [plone/volto#961] opened 2019-10-27 13:23 UTC
This URL that is used to get the values is wrong: http://localhost:8080/Plone/@vocabularies/http://localhost:8080/Plone/@sources/type_of_talk?b_start=0
The response obviously is `The vocabulary 'http:' does not exist`

![Screenshot_2019-10-27 Talk — Plone site(1)](https://user-images.githubusercontent.com/453208/67635264-300e4c80-f8c5-11e9-8a45-ae6ec02aa30b.png)

![Screenshot_2019-10-27 Talk — Plone site](https://user-images.githubusercontent.com/453208/67635265-30a6e300-f8c5-11e9-89e4-775f4771a8c9.png)

<img width="738" alt="Bildschirmfoto 2019-10-27 um 14 18 57" src="https://user-images.githubusercontent.com/453208/67635267-369cc400-f8c5-11e9-8a44-7f6793bdad3d.png">

**Comment by davisagli** [comment] 2023-09-14 05:25
Closing as a duplicate of https://github.com/plone/volto/issues/2604

**Closed by davisagli** 2023-09-14 05:25 UTC
Labels: 01 type: bug
