### ISSUE TITLE
Responsive Error in login page

### ISSUE THREAD

**Issue by chirag-23** [plone/volto#3250] opened 2022-04-15 10:08 UTC
**Login page shifts to left when width of screen decreases**
The Login div shifts to left of the screen when width of screen decreases to 767px or less, which according to me stay at centre.

**You can check your self**
Goto this url ~ https://6.demo.plone.org/login?return_url= 
reduce your screen width and see yourself.

*Screenshots*
![Screenshot 2022-04-15 at 3 30 01 PM](https://user-images.githubusercontent.com/76790227/163558464-ab29f9f9-4889-4625-93dd-7e42e1f8b673.png)
![Screenshot 2022-04-15 at 3 30 10 PM](https://user-images.githubusercontent.com/76790227/163558469-9647eb08-795e-4c5d-adfe-58df606b943e.png)

**Comment by suyashrastogi7** [comment] 2022-04-15 20:55
Hey, I have a way to fix this, Just by placing the login Container in a grid.

**Comment by dobri1408** [comment] 2022-05-05 08:18
@suyashrastogi7 I just submitted a different fix, which I think is better.

**Comment by alpha2207** [comment] 2022-12-24 07:08
I can solve it easily, Assign it to me.

**Comment by SaiRev0** [comment] 2023-01-14 11:11
Is the issue still open ?? if yes i would like to work on it

**Comment by tiberiuichim** [comment] 2023-01-14 13:19
@SaiRev0 Yes, it's still open. 

One of the core principles in Plone (Volto's backend, and by extension also Volto) is that our software is a do-ocracy. Things will get done only if we start working on them. So, really, there's no task in Volto that's off-limits. There are, though, limits to the things that can be approached, realistically, by new contributors. There's back history, context, understanding of the overall vision, etc, that all come with experience.

**Comment by tiberiuichim** [comment] 2023-01-14 13:22
Also, most important to read: https://6.dev-docs.plone.org/volto/developer-guidelines/contributing.html

**Comment by SaiRev0** [comment] 2023-01-16 10:50
@tiberiuichim Thanks, I m actually facing some issues in setting the repo in my local system so can you please help me out? is there any other way of communication other than here?

**Comment by tiberiuichim** [comment] 2023-01-16 11:00
@SaiRev0 see the plone discord. https://plone.org/news-and-events/news/2021/join-plone-chat-now-at-discord

**Comment by SaiRev0** [comment] 2023-01-17 20:36
@tiberiuichim I have fixed the issue, So now I have to make a pull request, So is there some specific way of making a pull request?

**Comment by SaiRev0** [comment] 2023-01-17 22:22
@tiberiuichim please check my pull request and review it.

**Comment by varun-s22** [comment] 2023-01-18 20:01
Is this issue still open? i think I can contribute

**Comment by lord2anil** [comment] 2023-01-22 13:01
is the issue is still open ??.i want to work on this

**Comment by stevepiercy** [comment] 2023-01-22 14:23
@lord2anil and @varun-s22 please read the history of this issue to answer your own question and learn how to contribute to this repository.

**Comment by HyperDanisH** [comment] 2023-02-23 06:19
Hi, I am still able to see this issue but have solved it and would like to contribute. Please assign me this issue.

Solved:-
![Plone-issue-soloved](https://user-images.githubusercontent.com/93310647/220833500-c64c2320-f656-446c-8be8-46d2006f4674.png)

**Comment by Shahbaz898414** [comment] 2023-02-24 20:22
I can solve it easily, Assign it to me.

**Comment by stevepiercy** [comment] 2023-04-01 03:19
The following pull requests are proposed solutions to this issue.

- https://github.com/plone/volto/pull/3252
- https://github.com/plone/volto/pull/4291
- https://github.com/plone/volto/pull/4309
- https://github.com/plone/volto/pull/4335
- https://github.com/plone/volto/pull/4437
- https://github.com/plone/volto/pull/4631

Before any pull requests can be considered by the Volto team, all the following requirements must be satisfied by all contributors.

1. Sign the [Plone Contributor Agreement](https://plone.org/foundation/contributors-agreement), and return it.
2. Open a pull request from your fork, not from the `volto` repository. This is a new requirement, for security purposes. Close any pull request made from the `volto` repository.
3. Follow [contributing guidelines for Volto](https://6.docs.plone.org/volto/developer-guidelines/contributing.html).

@alpha2207 @dobri1408 @suyashrastogi7 @VedantRaut-sudo @HyperDanisH @Shahbaz898414 @Monu01123

**Comment by SayanDeveloper** [comment] 2023-04-03 08:45
I have created a PR regarding this issue

Please check this out #4637

**Closed** 2023-09-09 16:04 UTC
Labels: 01 type: bug, 41 lvl: easy
