### ISSUE TITLE
You can't checkout a working copy of the site root

### ISSUE THREAD

**Issue by djay** [plone/volto#5992] opened 2024-04-30 04:54 UTC
**Describe the bug**
Users need a way to work on an alternative version of the homepage of the site while another version is live. this is currently not possible

**To Reproduce**
1. Turn on working copy
2. login and go to home page
3. Look at menus

**Expected behavior**
The normal actions to checkout and checkin a working copy

**Screenshots**
N/A

**Software (please complete the following information):**

- Volto Version [e.g. 8.5.0]
- Plone Version [e.g. 5.2.2]
- Plone REST API Version [e.g. 7.0.1]

**Additional context**

**Comment by davisagli** [comment] 2024-04-30 05:11
This is a duplicate of #5284

**Closed by davisagli** 2024-04-30 05:11 UTC
Labels: 01 type: bug
