### ISSUE TITLE
Change language, not updates string translated

### ISSUE THREAD

**Issue by giuliaghisini** [plone/volto#1848] opened 2020-09-25 15:09 UTC
In a site that uses Volto as a dependency (not directly in volto)
if i set in config: 
isMultilingual:true,
languages: ['it','en'],
defaultLanguage:'it'

i add some translation in some components, for example in a custom component used in footer, 
when i change language from languageSelector, the strings are not translated into the language selected, i still see the strings in previous language

**Comment by nileshgulia1** [comment] 2020-09-28 08:05
@giuliaghisini Did you get something like ```Missing message: "Open menu" for locale: "it", using default message as fallback.``` in the console?

**Comment by giuliaghisini** [comment] 2020-09-29 07:32
yes, but not when changing language, i get that message when loading page.

**Comment by giuliaghisini** [comment] 2020-09-29 07:32
did you have any idea?

**Comment by nzambello** [comment] 2020-10-01 12:54
We weren't dispatching the changeLanguage action, fixed internally, it was not a bug

**Closed by nzambello** 2020-10-01 12:54 UTC
Labels: 01 type: bug, 11 prio: blocker, 12 prio: high
