### ISSUE TITLE
Copied relative link is transformed to absolute link

### ISSUE THREAD

**Issue by tisto** [plone/volto#1529] opened 2020-05-27 07:16 UTC
When you edit a page and copy a relative link the pasted version is an absolute link that opens in a new tab.

Steps to reproduce:

1) Add a new page with a relative link to say, the "news" section in Plone and save
2) On the page view or on the edit view select and copy the link
3) create a new page and paste the link you copied, hit save
-> the link will not work after pasting

**Comment by iFlameing** [comment] 2020-05-29 10:10
@tisto can you tell me how I can reproduce it?

**Comment by nileshgulia1** [comment] 2020-09-14 10:50
@tisto Is this still an issue, cannot able to reproduce it.

**Comment by danalvrz** [comment] 2022-12-12 19:01
It’s not currently possible to enter a relative link at all, so I proceed to close this issue as not planned.

**Closed by danalvrz** 2022-12-12 19:01 UTC
Labels: 01 type: bug, 41 lvl: easy
