### ISSUE TITLE
User profile image is not displayed or deleted successfully from Volto UI

### ISSUE THREAD

**Issue by MostafaMagdyy** [plone/volto#5923] opened 2024-03-26 02:45 UTC
**Describe the bug**
User profile image is not displayed or deleted successfully from Volto UI. once you add a photo, Volto UI displays alt **user avatar** instead, and you cannot delete it successfully.

**To Reproduce**
1-In toolbar, open profile section.
2-Upload an image in portrait and save it.
3-Go back to home page and try to view your picture.
4-Notice the alt text instead of your picture.

**Expected behavior**
User picture should be displayed in profile section at toolbar.

**Screenshots**
![oie_TmNZo7AiQnh9](https://github.com/plone/volto/assets/97239596/3f3dafcc-0a6a-4f52-9c94-a385c08b95a1)

**Software (please complete the following information):**

- OS: [Ubuntu 22]
- Browser [Microsoft edge]
- Volto Version [18.0.0-alpha.25]
- Plone Version [6.0.10]
- Plone REST API Version [9.5.0]

**Comment by VenkateshSircilla123** [comment] 2024-04-03 18:14
its working fine in my laptop. profile pic is displayed

**Comment by davisagli** [comment] 2024-04-16 04:18
This is a duplicate of #1558 and #2927

**Closed by davisagli** 2024-04-16 04:18 UTC
Labels: 01 type: bug, needs: triage
