### ISSUE TITLE
You may need an appropriate loader to handle this file type

### ISSUE THREAD

**Issue by kartikpandey2** [plone/volto#589] opened 2019-01-01 14:50 UTC
I followed README to setup volto frontend locally but it's throwing error.
`On running yarn start  cmd`
![screenshot 132](https://user-images.githubusercontent.com/20434963/50573869-31382f80-0e02-11e9-9fe1-295e99836e55.png)
`localhost:3000`
![screenshot 131](https://user-images.githubusercontent.com/20434963/50573871-385f3d80-0e02-11e9-8e29-a7190dea01c6.png)

**Comment by sneridagh** [comment] 2019-01-09 09:19
@kartikpandey2 there's something strange in your build (there shouldn't be any text showing but some progress bars). I can see you are in Windows.

Are you following: 
https://training.plone.org/5/volto/index.html

Are you using create-volto-app package? Are you using the correct node version? It's like the less compiler webpack config is not being applied.

**Comment by nileshgulia1** [comment] 2019-01-14 14:33
@kartikpandey2  I cannot reproduce the error. Maybe try deleting `node_modules` and re-run `yarn` would solve the problem. I am closing this.

**Closed by nileshgulia1** 2019-01-14 14:33 UTC
