### ISSUE TITLE
Content locking integration is neded

### ISSUE THREAD

**Issue by tiberiuichim** [plone/volto#1522] opened 2020-05-26 10:39 UTC
Plone has a nice locking behaviour for content, benefit of plone.locking.

Volto has no integration with plone.locking. Content is not locked when it's being edited, blocks don't lock images if the link to them, etc. This is a major step back in what makes Plone an enterprise solution.

# Plone Classic Locking

1. login as user1 and edit a page (keep edit open, closing the browser seems to release the lock)
2. login as user2 and access the view of that page
3. user2 sees a message that the page is locked, edit icon is not shown in the toolbar

<img width="1438" alt="Bildschirmfoto 2021-06-26 um 20 31 54" src="https://user-images.githubusercontent.com/632105/123522450-a4fae080-d6bd-11eb-979e-53dae19ce8b6.png">

**Comment by avoinea** [comment] 2021-05-12 15:54
RestAPI support https://plonerestapi.readthedocs.io/en/latest/locking.html?highlight=locking

**Comment by tiberiuichim** [comment] 2021-05-12 19:15
oh yeah

**Comment by tisto** [comment] 2021-06-21 20:44
@tiberiuichim +1. Shouldn't be too hard to implement I guess, since we have the backend implementation in place.

**Comment by tisto** [comment] 2021-06-23 09:44
Duplicate of https://github.com/plone/volto/issues/1288. Closing.

**Comment by tisto** [comment] 2021-06-23 09:45
@tiberiuichim @avoinea sorry for the closing/opening. We should usually close the duplicate with the higher ID and not the original issue. Since you already closed the older issue, I left things as they are. We kind of need this in a current project. What about you folks? cc @nzambello @sneridagh

**Comment by tiberiuichim** [comment] 2021-06-23 11:29
It's a nice to have, for sure, but I think we should establish some UX guidelines for this. How should this look like? We could simply follow Plone's UX on this.

**Comment by tisto** [comment] 2021-06-26 19:35
@tiberiuichim I documented the current behavior of Plone classic. I think the UX is pretty straight forward and we can re-use the sticky messages that we use in the working copy support. I see this is on both the EEA and Red Turtle priorities. Maybe we can get together in the next weeks to discuss how we can make this happen... cc @sneridagh

**Comment by avoinea** [comment] 2021-09-07 18:32
Merged #2594

**Closed by avoinea** 2021-09-07 18:32 UTC
Labels: 04 type: enhancement
