### ISSUE TITLE
Search Block: Clicking the "x" inside the facet dropdown field does not remove the "x".

### ISSUE THREAD

**Issue by tisto** [plone/volto#2745] opened 2021-10-15 18:56 UTC
**Describe the bug**

Clicking the "x" inside the facet dropdown field does not remove the "x".

**To Reproduce**
1. Go to https://volto.kitconcept.dev/search-block
2. Choose any type facet
3. Click on the "x" within the type facet field
4. "x" does not go away

**Expected behavior**

"x" is removed.

**Screenshots**

![Search (2)](https://user-images.githubusercontent.com/632105/137537481-b5625544-36b3-4f2e-99c8-1a4fb0884201.png)

**Comment by tisto** [comment] 2021-10-15 18:56
@tiberiuichim ^^^

**Comment by tiberiuichim** [comment] 2021-10-16 05:34
@tisto I couldn't reproduce the issue with this PR: https://github.com/plone/volto/pull/2740

Could you give that one a try?

**Comment by ichim-david** [comment] 2023-10-12 15:47
@tisto this was fixed sometime as I am looking at your demo page and clicking on a selected value removes it and the x disappears.
I've tried with FF, Edge, and Safari and it works with all
https://volto.kitconcept.dev/blocks-examples/search-block#query=%5B%7B%22i%22%3A%22path%22%2C%22o%22%3A%22paqo.string.absolutePath%22%2C%22v%22%3A%22%2Fexamples%22%7D%2C%7B%22i%22%3A%22portal_type%22%2C%22o%22%3A%22paqo.selection.is%22%2C%22v%22%3A%22Collection%22%7D%2C%7B%22i%22%3A%22review_state%22%2C%22o%22%3A%22paqo.selection.is%22%2C%22v%22%3A%22spam%22%7D%2C%7B%22i%22%3A%22show_inactive%22%2C%22o%22%3A%22paqo.boolean.isTrue%22%2C%22v%22%3A%22%22%7D%5D&sort_order=descending

One thing I might complain perhaps as a new issue is that you see the x turn dark as if it's active but you cannot **Tab** to it and then press **Enter** to remove that selection.
You can remove the selection using **Backspace** but I wonder how many would know that and not try instead to operate with that x.
If you think it's worth it we can add an issue and see when it will be fixed.

**Comment by ichim-david** [comment] 2023-10-14 18:27
Closing as fixed in https://github.com/plone/volto/pull/2828

**Closed by ichim-david** 2023-10-14 18:27 UTC
Labels: 01 type: bug

**Comment by tisto** [comment] 2023-10-14 18:39
@ichim-david @tiberiuichim I can not reproduce this problem any longer:

https://volto.kitconcept.dev/blocks-examples/search-block#query=%5B%7B%22i%22%3A%22path%22%2C%22o%22%3A%22paqo.string.absolutePath%22%2C%22v%22%3A%22%2Fexamples%22%7D%2C%7B%22i%22%3A%22review_state%22%2C%22o%22%3A%22paqo.selection.is%22%2C%22v%22%3A%22external%22%7D%5D&sort_order=ascending

Thanks for you help here!
