### ISSUE TITLE
Multilingual: new translated object is created always in the LRF

### ISSUE THREAD

**Issue by giuliaghisini** [plone/volto#1400] opened 2020-04-21 13:49 UTC
- crate page A
- translate page A to another language
- create page B  inside page A 
- translate page B to another language
- the B-translated page is always placed in the LRF of the other language, and not into the same path of the original language as expected.

**Comment by sneridagh** [comment] 2020-04-21 15:07
Are you sure that "translated page A" is in place? Because we are using Plone's logic to control that, and the tests are in place, and I remember to test this use case successfully.

**Comment by sneridagh** [comment] 2020-04-21 17:10
@giuliaghisini crap, now I can't reproduce it anymore, it works always...
Any idea how to reproduce it? (I seen it myself at the first try, might be that I didn't had the lang set...)

**Comment by giuliaghisini** [comment] 2020-04-22 06:27
@sneridagh i tried again me too, but everything seems working well now.. i've done the same steps that i did yesterday but now it's everything ok.. I don't know what could be wrong in my previous tests.. i agree to schedule a meeting to discuss the language switch.

**Comment by giuliaghisini** [comment] 2020-04-22 06:53
@sneridagh i've reproduced the problem:

- crate page A
- translate page A to another language (well be page A1)
- create page B inside page A
- change lang from language switcher link in site header (the cookie 'lang' is changed to the correct destination language)
- edit the url in browser to return to page A (or B, it's the same). The cookie 'lang' is not changed now
- translate page B to another language
- the B-translated page is always placed in the LRF of the other language, and not into the same path of the original language as expected. Maybe because the cookie 'lang' is wrong and it's set to the previous language..

**Comment by sneridagh** [comment] 2020-04-22 14:52
>

> * crate page A
> 
> * translate page A to another language (well be page A1)
> 

What did you do here? Did you returned to the original language via the switcher?

> * create page B inside page A
> 
> * change lang from language switcher link in site header (the cookie 'lang' is changed to the correct destination language)
> 
> * edit the url in browser to return to page A (or B, it's the same). The cookie 'lang' is not changed now
> 
> * translate page B to another language
> 
> * the B-translated page is always placed in the LRF of the other language, and not into the same path of the original language as expected. Maybe because the cookie 'lang' is wrong and it's set to the previous language..

I guess we will need a video or so to make sure we are all in the same page and we can all reproduce the problem.

**Comment by sneridagh** [comment] 2020-05-06 15:42
@giuliaghisini can you try again? with https://github.com/plone/volto/pull/1450 might change things.

Also, if you can reproduce it again, it would be great to have a video with so we can review it!

**Comment by giuliaghisini** [comment] 2020-05-07 06:52
@sneridagh i tried again but the problem is still present. 
I created a video, how coluld i send it to you?.

**Comment by sneridagh** [comment] 2020-05-07 10:35
@giuliaghisini mmm slack?

**Comment by giuliaghisini** [comment] 2020-05-07 12:32
ok

**Comment by sneridagh** [comment] 2020-05-12 07:25
Fixed in #1468! Thanks @giuliaghisini for the support to find this nasty bug!

**Closed by sneridagh** 2020-05-12 07:25 UTC
Labels: 01 type: bug
