### ISSUE TITLE
Formating of date fields is very "basic", does not respect language

### ISSUE THREAD

**Issue by mck9** [plone/volto#987] opened 2019-10-31 15:12 UTC
e.g. start/end field of event accepts the german format "10.11.2020" (10th November) as input.
It is converted to: 2020-10-11 (11th October)
and is shown when editing the as: 2020-10-11T00:00:00+00:00

The same problem is on the fields "Publishing Date" and "Expiration Date".

volto 3.2.7 / Plone 5.1.6
volto 4.0.0-alpha.10 / Plone 5.2

**Comment by pnicolli** [comment] 2019-11-04 15:17
Possible duplicate of #678. See also #709.

**Comment by davisagli** [comment] 2023-09-14 05:35
This was improved, the date widget shows a localized date/time.

**Closed by davisagli** 2023-09-14 05:35 UTC
