### ISSUE TITLE
volto editor: clicking on a page in folder contents then go back to view

### ISSUE THREAD

**Issue by fredvd** [plone/volto#684] opened 2019-03-15 15:22 UTC
When I click on a page in a folder contents, I see the folder contents of the folderish page. 

![back_arrow_to_view](https://user-images.githubusercontent.com/394784/54442096-4b658680-473e-11e9-9a46-62574c1a0383.png)

Now how do I go back to viewing the page instead of its contents? I have to press the left back arrow in the top left menu.  I find this confusing as I'd associate arrow left as 'go back to where you were before', or maybe as  'go to the parent folder' when I see a folder contents.  

I do not associate  a left arrow symbol with 'view'.

**Comment by davisagli** [comment] 2023-09-14 05:05
Closing as a duplicate of https://github.com/plone/volto/issues/3713 which has more discussion and a draft PR.

**Closed by davisagli** 2023-09-14 05:05 UTC
Labels: 99 tag: UX
