### ISSUE TITLE
Event view should include calendar link to @@ics_view

### ISSUE THREAD

**Issue by tiberiuichim** [plone/volto#2539] opened 2021-06-22 06:48 UTC
We need a middleware to pipe the @@ics_view.

**Comment by tiberiuichim** [comment] 2021-06-22 08:17
```
import { getAPIResourceWithAuth } from '@plone/volto/helpers';

const HEADERS = ['content-type', 'content-disposition', 'cache-control'];

function icsViewMiddleware(req, res, next) {
  const { errorHandler } = req.app.locals;
  getAPIResourceWithAuth(req)
    .then((resource) => {
      // Just forward the headers that we need
      HEADERS.forEach((header) => {
        if (resource.headers[header]) {
          res.set(header, resource.headers[header]);
        }
      });

      res.send(resource.body);
    }, errorHandler)
    .catch(errorHandler);
}

function install(express) {
  const middleware = express.Router();

  middleware.all(['**/ics_view$', '**/@@ics_view$'], icsViewMiddleware);
  middleware.id = 'ics_view';
  return middleware;
}

export default function (config) {
  if (__SERVER__) {
    const express = require('express');
    config.settings.expressMiddleware = [
      ...(config.settings.expressMiddleware || []),
      install(express),
    ];
  }

  return config;
}
```

**Comment by tisto** [comment] 2022-04-09 10:33
@tiberiuichim this is a duplicate of https://github.com/plone/volto/issues/1764. If I am not mistaken we implemented this in one of our projects, right @sneridagh @ericof @jackahl? It should be in Volto core though.

**Closed by tisto** 2022-04-09 10:33 UTC
Labels: 04 type: enhancement
