### ISSUE TITLE
Sentry-support broke server hot-module-reload

### ISSUE THREAD

**Issue by datakurre** [plone/volto#2199] opened 2021-02-10 04:19 UTC
Volto server HMR (hot module reload) has been broken since Sentry-support was introduced.

I had to comment out lines

```js
// import initSentry from '@plone/volto/sentry';

// initSentry(Sentry);
```

at `./src/start-server.js` to get HRM back while running Volto in development mode.

**To Reproduce**

1. add custom middleware https://docs.voltocms.com/recipes/express/
2. start Volto development server
3. change middleware code
4. get error that server must be restarted for code to be reloaded

**Expected behavior**

Server should be reloaded on code change and changes be in effect after reload (HMR).

**Software (please complete the following information):**
 - Volto Version 10.10.0

**Comment by tiberiuichim** [comment] 2021-02-11 10:04
I've noticed HMR stopper working reliably. Super nice that you've traced it to the cause. Although I think sentry support is something that you want to have additional fail points, like lazy loading, it may be worth stripping it and moving it into an addon.

**Closed** 2022-12-15 04:51 UTC
Labels: 01 type: bug
