### ISSUE TITLE
Form Block

### ISSUE THREAD

**Issue by robgietema** [plone/volto#290] opened 2018-11-10 08:46 UTC

**Comment by avoinea** [comment] 2020-05-07 11:28
@robgietema Huh? Obsolete or it should be renamed to Form Block?!

**Comment by tisto** [comment] 2020-05-07 11:49
@avelino this ticket is from 2018...different times :)

**Comment by sneridagh** [comment] 2022-03-19 15:29
In 2022, https://github.com/collective/volto-form-block is candidate for core.

**Comment by davisagli** [comment] 2022-07-28 04:49
Closing as a duplicate of #739 which has more info

**Closed by davisagli** 2022-07-28 04:49 UTC
Labels: 04 type: enhancement, 12 prio: high, 21 status: confirmed, 43 lvl: complex
