### ISSUE TITLE
UX: Clear search input field consistency

### ISSUE THREAD

**Issue by tisto** [plone/volto#4769] opened 2023-05-16 06:43 UTC
**Describe the bug**

We currently show an "x" inside the search input field to clear the search input. Sometimes we place another "x" or trash can symbol next to this "x". This is confusing for the users.

**Comment by davisagli** [comment] 2023-05-16 07:05
@tisto What's an example of where this occurs?

**Comment by sharabhh** [comment] 2024-01-18 06:40
hello @tisto can you tell me an example of where this occurs, or how can i replicate it?

**Comment by syedfardeenjeelani** [comment] 2024-09-24 15:04
@tisto can you  please assign this issue to me ?

**Comment by davisagli** [comment] 2024-09-24 16:46
Closing the issue since @tisto didn't provide a full bug report with steps to reproduce, and it's not clear which search input he was talking about.

**Closed by davisagli** 2024-09-24 16:46 UTC
Labels: 01 type: bug, 99 tag: UX

**Comment by stevepiercy** [comment] 2024-09-24 21:40
@syedfardeenjeelani please read and follow [First-time contributors](https://6.docs.plone.org/contributing/first-time.html), especially [Things not to do](https://6.docs.plone.org/contributing/first-time.html#things-not-to-do), [Contributing to Plone](https://6.docs.plone.org/contributing/index.html), and [Contributing to Volto](https://6.docs.plone.org/contributing/volto.html).
