### ISSUE TITLE
Toolbar opening delay

### ISSUE THREAD

**Issue by singhcoder694** [plone/volto#5657] opened 2024-01-18 13:37 UTC
While I was working and going around the Plone site I found that clicking to toolbar button loads toolbar but with transition of 0.3s which could be good if it would be visible to user but, instead of that it can be seen it opens with delay of 0.3s which creates confusion for a while whether user clicked the button or not making it annoying. These tools on homepage are very frequent to use and shouldn't have trasition effects for more smooth and fast navigation across website.

Problem:
Slow load of toolbar div due to transition effect making it annoying for navigation.

Solution:
Remove transition or add another kind of transition for more visual and fast navigation.

https://github.com/plone/volto/assets/114601400/70ac7745-8ecf-4396-a259-b243ebb6e91c

When navigating around website this feature becomes annoying to use and leads to double click and that also closes the toolbar.... making user kind of frustrating (I faced this issue while navigating around website).

**Comment by AKA717** [comment] 2024-01-18 16:02
can you assign this to me?

**Comment by stevepiercy** [comment] 2024-01-18 20:33
@AKA717 please read and follow [Contributing to Plone](https://6.docs.plone.org/contributing/index.html) and [First-time contributors](https://6.docs.plone.org/contributing/first-time.html), especially [Things not to do](https://6.docs.plone.org/contributing/first-time.html#things-not-to-do).

**Comment by stevepiercy** [comment] 2024-01-19 12:04
@singhcoder694 before doing any work on this issue, please read and follow Item 2 in [Work with GitHub issues](https://6.docs.plone.org/contributing/first-time.html#work-with-github-issues).

I see you already created a pull request with your proposed fix, but in the future to avoid extra work, it is a good idea to discuss and determine what, if anything, needs to be done before you do any work.

**Comment by AKA717** [comment] 2024-01-19 13:22
Sorry for that it won't happen again and thank you for the valuable
guidance.

**Comment by singhcoder694** [comment] 2024-01-19 13:27
@stevepiercy got it and joined groups, thankyou for informing about this. From next time I would discuss and create issues if required...

**Comment by ichim-david** [comment] 2024-01-21 08:47
@singhcoder694 as a newcomer trying to get your first contribution in please read the docs carefully.
https://6.docs.plone.org/contributing/first-time.html#work-with-github-issues
"2. Discuss whether you should perform any work"
Before trying to work on an issue that you think you found, open the issue first and see if there is any consensus
in fixing that issue.
Sometimes what can appear as a bug for you could be a feature that works as intended.

In order to avoid extra work that has a low chance of getting merged, consider raising the issue first and waiting to
work on it until you get some feedback from the community.

For instance your perceived delay is a transition added on the dropdowns to have a smooth opening and closing
effect rather than the hard show and hide.

There are some instance where you want to avoid transitions in which case it would be handled within a media
query prefers-reduced-motion but if that is the route it needs to be approved and changed in other places as well.

I am closing this issue, if you really want to contribute to this project then consider this advice:

Want to work on something?
Start with something easy first, an issue that has the easy label
[41 lvl: easy
](https://github.com/plone/volto/labels/41%20lvl%3A%20easy)

Want to help?
Look at the tickets where help is asked as long as you have the knowledge to help
[31 needs: help ](https://github.com/plone/volto/labels/31%20needs%3A%20help)

**Closed by ichim-david** 2024-01-21 08:47 UTC
