### ISSUE TITLE
Going from page A to search results view to search result page B makes the A page be shown for a fraction of second before B loads

### ISSUE THREAD

**Issue by silviubogan** [plone/volto#2186] opened 2021-02-03 10:21 UTC
**Describe the bug**
Going from page A to search results view to search result page B makes the A page be shown for a fraction of second before B loads

**To Reproduce**
1. Go to https://volto.kitconcept.com/
2. Type in search box in header `plone`
3. Wait for the search results to be shown
4. Click on the first search result
5. See that the home page is shown for a fraction of second before the first search result's page is shown

**Expected behavior**
A spinner, progress bar or some loading indicator to be shown instead of the home page while the user goes from the search results page to the first result's page.

**Software (please complete the following information):**
 - OS: Manjaro Linux
 - Browser: Chromium, Firefox
 - Volto Version
     - 10.3.0
     - 11.0.0
 - Plone Version 5.2.2
 - Plone REST API Version - I do not know where to find this piece of information

If requested, I can make a GIF showing the issue.

**Comment by tiberiuichim** [comment] 2021-02-03 15:43
Duplicate of https://github.com/plone/volto/issues/1070

**Closed by tiberiuichim** 2021-02-03 15:43 UTC
Labels: 01 type: bug
