### ISSUE TITLE
Remove toast notification of logged out when you login once again.

### ISSUE THREAD

**Issue by iFlameing** [plone/volto#4125] opened 2022-12-15 11:58 UTC
Steps to Reproduce.

1. Create a page.
2. logout
3. login again
4. You still see the logout notification.

**Comment by CannedShroud** [comment] 2022-12-17 12:24
I could not reproduce this

**Comment by davisagli** [comment] 2022-12-20 06:33
Fixed in #4126 and #4136

**Closed by davisagli** 2022-12-20 06:33 UTC
Labels: 01 type: bug
