### ISSUE TITLE
HTML Tile

### ISSUE THREAD

**Issue by robgietema** [plone/volto#292] opened 2018-11-10 08:48 UTC

**Comment by luckykumardev** [comment] 2018-12-25 18:35
@robgietema  can you please explain what the issue is?

**Comment by ajayns** [comment] 2018-12-26 04:12
This issue has already been resolved with PR #307 do give it a check if you wanna know what the issue is about!

**Comment by sneridagh** [comment] 2019-03-02 16:58
Closing, since already merged!

**Closed by sneridagh** 2019-03-02 16:58 UTC
Labels: 04 type: enhancement, 13 prio: normal, 21 status: confirmed, 41 lvl: easy
