### ISSUE TITLE
SearchTags uses invalid vocabulary API

### ISSUE THREAD

**Issue by tiberiuichim** [plone/volto#3455] opened 2022-07-02 10:32 UTC
https://github.com/plone/volto/blob/f2f1b1e6ed5039d08f1a4477b1dbee07c9bec321/src/components/theme/Search/SearchTags.jsx#L66

It appears the state has vocab.items, not vocab.terms.

There's no terms in the vocab reducer: https://github.com/plone/volto/blob/f2f1b1e6ed5039d08f1a4477b1dbee07c9bec321/src/reducers/vocabularies/vocabularies.js#L80

**Comment by Player256** [comment] 2022-07-10 06:28
Hello there, I am interested in working on this issue. I was going through the code (specifically the file volto/src/components/theme/Search/SearchTags.jsx ) . Should I try replacing 'terms' with 'items' `state.vocabularies[vocabulary] && state.vocabularies[vocabulary].terms` .

**Comment by tiberiuichim** [comment] 2022-07-10 15:39
@Player256 Yes, but also "get to the root of the problem", to say so. It would be good to know when this problem appeared and why was it ignored so long (probably no test, in which case a text would be good to have). Notice that another change is needed rendering the tag, so that it's properly rendered (I think "title" instead of "label" or something along those lines).

**Comment by silviubogan** [comment] 2022-10-07 19:43
@tiberiuichim The Git history of the SearchTags.jsx file shows that from the start of the existence of this file `terms` was used, not `items`.

In the history of vocabularies.js reducers file the change is introduced in https://github.com/plone/volto/commit/3b50e491c859cd80718fa87205f70f86ea0746fb#diff-c447889751e6aadd2e53629d3c7d10bb20eb4a2a3540fa0d22376a0bd1c91f62L36 .

The unit tests for the reducer and the SearchTags component handle this type of situation well.

I have a working SearchTags.jsx file and I will work on a SearchTags.test.jsx file with which I can make a PR.

I have trouble running Jest with `yarn test` in the current Volto `master` clone.

**Comment by silviubogan** [comment] 2022-10-09 13:45
@tiberiuichim The root of the problem is that at the commit of the change with `items` the unit test for the vocabularies reducer was already failing with this error masking the new error:

![image](https://user-images.githubusercontent.com/198924/194759373-d25f374b-edfe-4180-b987-fdcaebafbfc0.png)

See https://github.com/plone/volto/blob/3b50e491c859cd80718fa87205f70f86ea0746fb/src/reducers/vocabularies/vocabularies.test.js#L25

I am working on the PR.

**Comment by tiberiuichim** [comment] 2022-10-09 14:19
@silviubogan Please try to keep your changes limited to the SearchTags component, don't change the API of the vocabulary reducer, as it's being used in many other places.

**Comment by silviubogan** [comment] 2022-10-09 14:44
@tiberiuichim OK, PR done: https://github.com/plone/volto/pull/3743.

**Comment by davisagli** [comment] 2022-10-22 16:28
Fixed in #3743

**Closed by davisagli** 2022-10-22 16:28 UTC
Labels: 01 type: bug, 41 lvl: easy
