### ISSUE TITLE
BUG REPORT: The sidebar pop-ups are not functioning correctly

### ISSUE THREAD

**Issue by kanhaiya04** [plone/volto#5787] opened 2024-02-22 19:47 UTC
**Describe the bug**
After logging in, if I click on the profile, add, or more icons in the sidebar, the respective pop-ups open up. However, clicking on them again doesn't close the pop-ups; I have to click outside somewhere to close them.

**To Reproduce**

1. Login to volto
2. Click on the profile, add, or more icon
3. Try to close the pop-up by clicking again on it
4. It won't work

**Expected behavior**
Clicking again to the same icon should close the pop-up

**Screenshots**

https://github.com/plone/volto/assets/93936630/7b1321cf-d8b2-42db-bc59-23ff6c7abf99

**Software (please complete the following information):**

- Volto Version [e.g. 8.5.0]
- Plone Version [e.g. 5.2.2]
- Plone REST API Version [e.g. 7.0.1]

**Additional context**

**Comment by kanhaiya04** [comment] 2024-02-22 19:49
Seeking the maintainer's perspective before moving forward with this.

**Comment by stevepiercy** [comment] 2024-02-22 21:49
Closing as duplicate of #5645. Please search the issue tracker for similar issues before opening a new one. Thank you!

**Closed by stevepiercy** 2024-02-22 21:49 UTC
Labels: 01 type: bug

**Comment by kanhaiya04** [comment] 2024-02-23 19:19
I inquired about this bug in the Discord community before opening the issue, but I forgot to check for similar issues. I'll be sure to keep that in mind next time.
