### ISSUE TITLE
Why is getContent ?fullobjects by default?

### ISSUE THREAD

**Issue by tiberiuichim** [plone/volto#1912] opened 2020-10-18 05:33 UTC
I have a folder with around 30 children. Each of these children is a full page, a lot of text, many many blocks, some of the blocks embed data (which I'll have to optimize), etc. "Big Volto", to say so. Viewing each of these children, on its own, is fine, but when I look at the parent folder, it downloads all the data, including everything for its children.

I don't think it's needed. I think the children should be summarized, not listed in full, by default. If there are pages that need the full list of children, those should do a separate getContent with full object.

I was thinking that it would be nice to declare, per view, what types of getContent and expands it wants so that they can be prefetched, but the view is determined only after the getContent is performed. We could automate this, but it wouldn't be optimal, there would be duplicate requests.

**Comment by tisto** [comment] 2020-10-18 07:02
@tiberiuichim this is a hard problem that we also have in our larger deployments. If I am not mistaken the preview images are the main reason we have to fetch fullobjects in most cases, is that correct @sneridagh?

**Comment by sneridagh** [comment] 2020-10-18 07:32
I barely can recall why we forced that, probably because of the listing views generated when accessing the parent. Which we can now replace them with listing blocks (or alike). We can remove it and see how it behaves.

@tiberiuichim agreed that we need a way to infer this "actions modifiers" (I think they are more use cases, right?) the problem is how to do that in an elegant way.

**Comment by tiberiuichim** [comment] 2020-10-18 10:05
For the moment, to quickfix my problem:

- I've added a custom block serializer transformer that removes the big blob data from the block data, on content serialization
- I've created a simple `@blocks` endpoint that can give me raw data from a block
- Add a new action + reducer to fetch the block data from the `@blocks` endpoint and I've wrapped my blocks in a custom HOC that will do that

I realize that I'd like to have this behavior built into Volto. My idea would be like this, and it's something that I've explored at one point around a year ago:

- we have a custom "attachments" endpoints, it stores data into blobs. This is achieved using annotation storage on each context
- the blocks will have a smart field "blobs", where they can place "big data". On the backend this data is offloaded to the attachments annotation storage. Each block gets its own dedicated entry in the attachment storage, so whenever a block is not found (on patch operations), its attachments will be removed.

**Comment by pnicolli** [comment] 2020-11-17 14:58
@sneridagh I like the idea of removing it and seeing how it behaves.
Image miniature urls can still be generated with ``${context_url}/@@images/image/${miniature}``. It might no be ideal, but still working if needed.

**Comment by cekk** [comment] 2020-11-17 15:18
+1 for removing fullobjects..we have the same problem as @tiberiuichim : several subfolders with a lot of additional fields and blocks that we don't need, and the get of their parent took ~ 2s to return the data.

**Comment by sneridagh** [comment] 2020-11-17 15:39
If you've tested it and it works fine, I'm +1 to remove it, but I would make it an opt-in just in case. We also have the "extenders" and eventually come up with a plan for the "smart extenders".

@tiberiuichim btw, what happened with the "tentative image transformer"?

**Comment by sneridagh** [comment] 2020-11-17 16:55
@iFlameing adding a link is also broken, and the callout is totally broken when used with inline styles too.

**Comment by tiberiuichim** [comment] 2020-11-17 17:02
@sneridagh nothing moved further with the image transformers. I'm actually thinking I should go back for a bit to do some backend work... there's still room for improvement in the backend, most important the "smart fields" idea, it need to further evolve it to have more smart fields

**Comment by cekk** [comment] 2020-11-18 13:31
> If you've tested it and it works fine, I'm +1 to remove it, but I would make it an opt-in just in case. We also have the "extenders" and eventually come up with a plan for the "smart extenders".
> 

Not yet, we need to test it a bit..and we already thinked about it as an opt-in ;)

**Comment by tiberiuichim** [comment] 2020-11-18 14:03
I think this opt-in should be the default. It would rather be an "opt-out".

All of us don't want this behavior by default. All of us consider Volto as offering a performance improvement over Plone, but if the default for all the upcoming projects will be that it performs worse then Plone, what good would that do?

I propose that we really identify the projects that use this broken full_objects behavior and see if they need help migrating. Don't keep things fundamentally broken just for the sake of not breaking stuff.

**Comment by tiberiuichim** [comment] 2020-11-25 07:16
I'm bumping up priority of this because it's highly annoying and will only lead to broken sites everywhere.

As an example of how wrong it is to rely on getContent() to give you the items for a listing, well, you'll only get the first 25 items (default set in plone.restapi), then you'll have to batch the next 25 and so on. So in any case, if you're using getContent to create listings of children, you'll end up with the wrong thing outside the most simplest cases.

**Comment by sneridagh** [comment] 2020-11-28 12:13
Closed by: https://github.com/plone/volto/pull/2026

**Closed by sneridagh** 2020-11-28 12:13 UTC
