### ISSUE TITLE
Option to open /edit at same position as /view

### ISSUE THREAD

**Issue by ksuess** [plone/volto#4266] opened 2023-01-17 15:17 UTC
This would mean
- disabling ScrollToTop (for /edit, per content type),
- some configuration to prevent that a block is selected (per content type).

**Comment by davisagli** [comment] 2023-01-17 15:27
@ksuess Closing as a duplicate of #4266. I will copy your notes there because they are helpful.

**Closed by davisagli** 2023-01-17 15:27 UTC
Labels: 04 type: enhancement
