### ISSUE TITLE
Placeholder for text block has been replaced by form title

### ISSUE THREAD

**Issue by tiberiuichim** [plone/volto#2322] opened 2021-03-30 14:18 UTC
Since the BlocksForm refactoring, the placeholder for the text is now the form title:

![Screenshot_20210330_171701](https://user-images.githubusercontent.com/141568/113003968-e5f55e80-917b-11eb-9f60-103bfcc0b591.png)

The placeholder should be "Type text..."

**Comment by avoinea** [comment] 2021-03-30 17:25
Hmm, true.

The problem is that I need this behavior in order to be able to override placeholder to existing and new text blocks within a Column / Group.

I can revert it for now for DraftJS, or we can add new props... :thinking:

**Comment by avoinea** [comment] 2021-03-30 18:07
Ok, the fix was simpler. The Form.jsx title and description shouldn't have been passed to the BlocksForm https://github.com/plone/volto/commit/5c04fec1fde1d08021f891a0e0a9b9814355a505#

**Comment by nileshgulia1** [comment] 2021-04-01 07:57
fixed by #2323

**Closed by nileshgulia1** 2021-04-01 07:57 UTC
Labels: 01 type: bug
